openapi: 3.0.3
info:
  title: zkPrivatePay Gateway API
  version: 0.1.0
servers:
  - url: https://localhost:8080/api
paths:
  /proofs/payment:
    post:
      summary: Generate a confidential payment proof (dev only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Proof bundle
  /proofs/kyc:
    post:
      summary: Generate a selective disclosure KYC proof (dev only)
      responses:
        '200':
          description: Proof bundle
  /payments/intent:
    post:
      summary: Submit a payment intent
      responses:
        '200':
          description: OK
  /clob/order:
    post:
      summary: Submit private order commitment
      responses:
        '200':
          description: OK
  /analytics/aggregate:
    get:
      summary: Privacy-preserving aggregated metrics (zk-attested in prod)
      responses:
        '200':
          description: OK
